export let listLinks = {
    "Конфликт": "Conflict",
    "Трехактная структура": "ThreeActStructure",
    "Разоблачение-Раскрытие": "TheReveal",
    "Кульминация": "TheClimax",
    "Развязка": "Denouement",
    "Конец": "TheEnd",
    "Чеховский пистолет": "ChekhovsGun",
    "МакГаффин": "MacGuffin",
    "Предыстория": "Backstory",
    "Реткон": "Retcon",
    "Сюжетная арка": "StoryArc",
    "Романтическая арка": "RomanceArc",
    "Любовный треугольник": "LoveTriangle",
    "Наступает веселье": "HilarityEnsues",
    "Эзоп": "AnAesop",
    "Серьезное дело": "SeriousBusiness",
    "Маскарад": "Masquerade",
    "Перенос в КОСМОС": "RecycledINSPACE",
    "X встречает Y": "tvtropes.org / pmwiki / pmwiki.php / JustForFun / XMeets",
    "Магия А есть Магия А": "MagicAIsMagicA",
    "Скользящая шкала идеализма против цинизма": "SlidingScaleOfIdealismVersusCynicism",
    "Статус-кво — это Бог": "StatusQuoIsGod",
    "Призыв к приключениям": "CallToAdventure",
    "Квест искупления": "RedemptionQuest",
    "Путешествие героя": "TheHerosJourney",
    "Спасение мира": "SavingTheWorld",
    "Они борются с преступностью": "TheyFightCrime",
    "Наковальня": "Anvilicious",
    "За гранью невозможного": "BeyondTheImpossible",
    "Пересекает черту дважды": "CrossesTheLineTwice",
    "Убежище в Дерзость": "RefugeInAudacity",
    "Темнее и острее": "DarkerAndEdgier",
    "Винт разума": "MindScrew",
    "Мирское стало удивительным": "MundaneMadeAwesome",
    "Фансервис": "Fanservice",
    "Слезоточивый придурок": "TearJerker",
    "Вангст": "Wangst",
    "Прыжок через акулу": "JumpingTheShark",
    "Отращивание бороды": "GrowingTheBeard",
    "Прикладной флеботин": "AppliedPhlebotinum",
    "Техно лепет": "TechnoBabble",
    "Ручная волна": "HandWave",
    "Deus Ex Machina": "DeusExMachina",
    "Достать из задницы": "AssPull",
    "Запечатанное зло в банке": "SealedEvilInACan",
    "Артефакт Судьбы": "ArtifactOfDoom",
    "Гамбит Ксанатоса": "XanatosGambit",
    "Большие проклятые герои": "BigDamnHeroes",
    "Погладить собаку": "PetTheDog",
    "Пни собаку": "KickTheDog",
    "Моральный горизонт событий": "MoralEventHorizon",
    "Герой": "TheHero",
    "Антигерой": "AntiHero",
    "Идиот Герой": "IdiotHero",
    "Супергерой": "Superhero",
    "Малыш-герой": "KidHero",
    "Хитрый герой": "GuileHero",
    "Трагический герой": "TragicHero",
    "Рыцарь в сияющих доспехах": "KnightInShiningArmor",
    "Избранный": "TheChosenOne",
    "Девченка с яйцами": "ActionGirl",
    "Отважная девушка": "PluckyGirl",
    "Определитель": "Determinator",
    "Гений Громила": "GeniusBruiser",
    "Группа из пяти человек": "FiveManBand",
    "Крутой книжный червь": "BadassBookworm",
    "Технопацифист": "TechnicalPacifist",
    "Туз": "TheAce",
    "Капитан": "TheCaptain",
    "Стрелок": "TheGunslinger",
    "Бесстрашный репортер": "IntrepidReporter",
    "Авантюрист-археолог": "AdventurerArchaeologist",
    "Главный герой": "TheProtagonist",
    "Идиотский мяч": "IdiotBall",
    "Фландеризация": "Flanderization",
    "Задира": "Badass",
    "Кнопка берсерка": "BerserkButton",
    "Придурок с золотым сердцем": "JerkWithAHeartOfGold",
    "Придурок": "Jerkass",
    "Подкованный в жанре": "GenreSavvy",
    "Поворот лица пяткой": "HeelFaceTurn",
    "Антагонист": "TheAntagonist",
    "Вуби": "TheWoobie",
    "Облачный Кукушонок": "CloudCuckooLander",
    "Большой Окорок": "LargeHam",
    "Округлый характер": "RoundedCharacter",
    "Плоский персонаж": "FlatCharacter",
    "Динамичный характер": "DynamicCharacter",
    "Статичный характер": "StaticCharacter",
    "Поворот лицом к пятке": "FaceHeelTurn",
    "Безумный Ученый": "MadScientist",
    "Мэри Сью": "MarySue",
    "Мудаки": "Mooks",
    "Краснорубашечники": "RedShirt",
    "Магглы": "Muggles",
    "Лоскутный": "TheScrappy",
    "Ансамбль Темная лошадка": "EnsembleDarkhorse",
    "Любимец Создателя": "CreatorsPet",
    "Цундере": "Tsundere",
    "Эксцентричный наставник": "EccentricMentor",
    "Тупой качек": "DumbMuscle",
    "Нежный великан": "GentleGiant",
    "Дурак": "TheFool",
    "Перебежчик": "Turncoat",
    "Несчастные влюбленные": "StarCrossedLovers",
    "Рассказчик": "TheStoryteller",
    "Лидер повстанцев": "RebelLeader",
    "Мятежный дух": "RebelliousSpirit",
    "Недотепа": "TheKlutz",
    "Симпатичный разбойник": "LoveableRogue",
    "Человек массового уничтожения": "PersonOfMassDestruction",
    "Большой плохой": "BigBad",
    "Великолепный ублюдок": "MagnificentBastard",
    "Манипулятивный ублюдок": "ManipulativeBastard",
    "Гроссмейстер": "TheChessmaster",
    "Полный монстр": "CompleteMonster",
    "Маньяк-убийца": "OmnicidalManiac",
    "Рыцарь-тамплиер": "KnightTemplar",
    "Злой близнец": "EvilTwin",
    "Враг внутри": "EnemyWithin",
    "Аморальный адвокат": "AmoralAttorney",
    "Обструктивный бюрократ": "ObstructiveBureaucrat",
    "Злая мачеха": "WickedStepmother",
    "Скотина": "TheBrute",
    "Жуткий ребенок": "CreepyChild",
    "Заклятый враг": "ArchEnemy",
    "Дракон": "TheDragon",
    "Крот": "TheMole",
    "Вирус": "TheVirus",
    "Жуткая мерзость": "EldritchAbomination",
    "Однокрылый Ангел": "OneWingedAngel",
    "Коррумпированный корпоративный руководитель": "CorruptCorporateExecutive",
    "Империя": "TheEmpire",
    "Антизлодей": "AntiVillain",
    "Злодей Главный герой": "VillainProtagonist",
    "Для Эвулза": "ForTheEvulz",
    "Злой смех": "EvilLaugh",
    "Ты подвел Меня": "YouHaveFailedMe",
    "Кот справа": "RightHandCat",
    "Троп": "Trope",
    "Висящий абажур": "LampshadeHanging",
    "Оправданный троп": "JustifiedTrope",
    "Извращенный троп": "SubvertedTrope",
    "Самые старые в книге": "TheOldestOnesInTheBook",
    "Правило крутости": "RuleOfCool",
    "Правило смешного": "RuleOfFunny",
    "Правило драмы": "RuleOfDrama",
    "Четвертая стена": "FourthWall",
    "Правда на телевидении": "TruthInTelevision",
    "Реальность нереальна": "RealityIsUnrealistic",
    "Как реальность, если не указано иное": "LikeRealityUnlessNoted",
    "Антропный принцип": "AnthropicPrinciple",
    "Закон сохранения деталей": "TheLawOfConservationOfDetail",
    "Гипотеза литературного агента": "LiteraryAgentHypothesis",
    "Моральный диссонанс": "MoralDissonance",
    "Пародийная таблица стихий": "ParodicTableOfTheElements",
    "Канон": "Canon",
    "Выкрикивать": "ShoutOut",
    "Возьми это": "TakeThat",
    "Провал критического исследования": "CriticalResearchFailure",
    "Зрители - Дебилы": "ViewersAreMorons",
    "Писатель на борту": "WriterOnBoard",
    "Вмешательство руководства": "ExecutiveMeddling",
    "Пропускание Дерьма Мимо ушей": "GettingCrapPastTheRadar",
    "Ад разработки": "DevelopmentHell",
    "Облажались в сети": "ScrewedByTheNetwork",
    "Фанон": "Fanon",
    "Добровольное прекращение недоверия": "WillingSuspensionOfDisbelief",
    "Логика холодильника": "FridgeLogic",
    "Эпилептические деревья": "EpilepticTrees",
    "Драко в кожаных штанах": "DracoInLeatherPants",
    "Меметическая мутация": "MemeticMutation",
    "Слово Божье": "WordOfGod",
    "Мантра MST3K": "MST3KMantra",
    "Быстрый": "Squick",
    "Фрейд был прав": "FreudWasRight"
};